name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write kubeconfig file
        run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig

      - name: Debug kubeconfig content
        run: cat kubeconfig

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.24.0'

      - name: Validate Kubernetes config
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: kubectl get nodes

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: kubectl apply -f nginx.yaml
