name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Start de pipeline bij een push naar de main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Code ophalen
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Kubernetes configuratie instellen
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      # 3. Kubectl installeren
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.28.0'

      # 4. Validatie van Kubernetes manifests
      - name: Validate Kubernetes manifests
        run: kubectl apply --dry-run=client -f ./k8s-manifests/

      # 5. Deployen naar Kubernetes
      - name: Deploy to Kubernetes
        run: kubectl apply -f ./k8s-manifests/
